---
- hosts: localhost
  become: true
  tasks:
#   - name: Install Paru Package Manager
#     package:
#       name: paru
#       state: present
    
  - name: Install Packages
    shell: "yes 'y' | paru -S --skipreview {{ item }}"
    with_items:
    - tmux
    - zsh
    - joplin-desktop
    - vivaldi
    - fish-git
    - guake
    - podman
    - cowsay
