---
- hosts: localhost
  tasks:
  - name: install packages
    command: yes | paru -S {{ item }}
    with_items:
    - tmux
    - zsh
    - joplin-desktop
    - vivaldi
    - visual-studio-code-insiders
    - guake
