---
- hosts: localhost
  become: true
  tasks:
  - name: install packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - tmux
    - zsh
    - joplin-desktop
    - vivaldi
    - fish-git
    - guake
    - podman
    - cowsay
