---
# https://sourceforge.net/projects/garuda-linux/files/gnome-barebones/210225/garuda-gnome-barebones-linux-lts-210225.iso
# ansible-pull --ask-become-pass -vvv -U https://github.com/ph-One/workstation.git
- hosts: localhost
  tasks:
  
  - name: Setup Log File
    become: yes
    ansible.builtin.file:
      path: /tmp/install.log
      state: touch
      owner: root
      group: root
      mode: '0777'

  - name: Install Paru Package Manager
    shell: "yes '' | pacman -S {{ item }} 2>&1 | tee -a /tmp/install.log"
    become: yes
    with_items:
    - paru
    - base-devel
  
  - name: Update System Packages
    shell: "yes '' | paru -Syyu 2>&1 | tee -a /tmp/install.log"

  - name: Generate Package List
    set_fact:
      pkgList:
      - cbonsai
      - tmux
      - zsh
      - joplin-desktop
      - vivaldi
      - fish-git
      - guake
      - nvidia-dkms
      - rustup
      - telegram-desktop
      - ttf-iosevka
      - libvirt
      - virt-manager
      - vlc
      - xdotool
      - yq
      - podman
      - cowsay
      - firmware-manager
      - libfirmware-manager
      - kubectl
      - visual-studio-code-insiders-bin
      - esanso-bin
      - bpytop
      - htop
      - nvtop
      - chromium
      - flameshot
      - jq
      sys76List:
      - sys76-kb
      - system76-apci-dkms
      - system76-dkms
      - system76-driver
      - system76-firmware-daemon
      - system76-io-dkms
      - system76-kbd-led-git
      - system76-power
      smartCardReaderList:
      - ccid
      - opensc
      - icaclient
      - pcsc-tools

  - name: Install System76 Packages (bonw14)
    shell: "yes '' | paru -S --skipreview {{ item }} 2>&1 | tee -a /tmp/install.log"
    with_items:
    - "{{ pkgList | join(' ') }}"
    - "{{ sys76List | join(' ') }}"
    - "{{ smartCardReaderList | join(' ') }}"
    
  - name: Setup ICA Client
    shell: |
      mkdir -p $HOME/.ICAClient/cache
      cp /opt/Citrix/ICAClient/config/{All_Regions,Trusted_Region,Unknown_Region,canonicalization,regions}.ini $HOME/.ICAClient

  - name: Start and Enable sshd Service
    become: yes
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: sshd
      
  - name: Start and Enable SmartCard Service
    become: yes
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: pcscd.service

  - name: Start and Enable System76 Power Service
    become: yes
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: system76-power.service

  - name: Start and Enable System76 Service
    become: yes
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: system76

  - name: Start and Enable System76 Firmware Deamin Service
    become: yes
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: system76-firmware-daemon.service
