---
# https://sourceforge.net/projects/garuda-linux/files/gnome-barebones/210225/garuda-gnome-barebones-linux-lts-210225.iso
# sudo pacman -S ansible-base
# ansible-pull --ask-become-pass -vvv -U https://github.com/ph-One/workstation.git
- hosts: localhost
  tasks:
  
  - name: Setup Log File
    become: yes
    ansible.builtin.file:
      path: /tmp/install.log
      state: touch
      owner: root
      group: root
      mode: '0777'

#   - name: Install Paru Package Manager
#     shell: "yes '' | pacman -S --needed {{ item }} 2>&1 | tee -a /tmp/install.log"
#     become: yes
#     with_items:
#     - paru
#     - 
  
  - name: Update System Packages
    shell: "yes '' | paru -Syyu --skipreview --needed 2>&1 | tee -a /tmp/install.log"

  - name: Generate Package List
    set_fact:
      pkgList:
      - base-devel
      - btop
      - esanso-bin
      - flameshot
      - guake
      - joplin-desktop
      - jq
      - kubectl
      - libvirt
      - nvidia-dkms
      - nvtop
      - podman
      - virt-manager
      - visual-studio-code-insiders-bin
      - vivaldi
      - yq
      - zellij
      - zsh
      smartCardReaderList:
      - ccid
      - icaclient
      - opensc
      - pcsc-tools

  - name: Setup ICA Client
    shell: |
      mkdir -p $HOME/.ICAClient/cache
      cp /opt/Citrix/ICAClient/config/{All_Regions,Trusted_Region,Unknown_Region,canonicalization,regions}.ini $HOME/.ICAClient

  - name: Install Packages
    shell: "yes '' | paru -S --needed --skipreview {{ item }} 2>&1 | tee -a /tmp/install.log"
    with_items:
    - "{{ pkgList | join(' ') }}"
    - "{{ smartCardReaderList | join(' ') }}"

  - name: Start and Enable sshd Service
    become: yes
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: sshd
      
  - name: Start and Enable SmartCard Service
    become: yes
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: pcscd.service
