---
- hosts: localhost
  become: yes
  tasks:

  - name: Install Paru Package Manager
    package:
      name: paru
      state: present
    
  - name: Install Development Packages
    package:
      name: base-devel
      state: present

  - name: Generate Package List
    set_fact:
      pkgList:
      - cbonsai
      - tmux
      - zsh
      - joplin-desktop
      - vivaldi
      - fish-git
      - guake
      - nvidia
      - podman
      - cowsay
      - firmware-manager
      - libfirmware-manager
      - kubectl
      - visual-studio-code-insiders-bin
      - esanso-bin
      sys76List:
      - sys76-kb
      - system76-apci-dkms
      - system76-dkms
      - system76-driver
      - system76-firmware-daemon
      - system76-io-dkms
      - system76-kbd-led-git
      - system76-power
      smartCardReaderList:
      - opensc
      - icaclient
      - pcsc-tools

  - name: Install System76 Packages (bonw14)
    shell: "yes 'y' | paru -S --skipreview {{ item }}"
    with_items:
    #- "{{ pkgList | join(' ') }}"
    #- "{{ sys76List | join(' ') }}"
    - "{{ smartCardReaderList | join(' ') }}"
