---
# https://sourceforge.net/projects/garuda-linux/files/gnome-barebones/210225/garuda-gnome-barebones-linux-lts-210225.iso
- hosts: localhost
  become: yes
  tasks:
  - name: Create Log File
    ansible.builtin.file:
      path: /tmp/install.log
      owner: kmatheny
      group: kmatheny
      state: touch
      mode: u=rw,g=rw,o=rw

  - name: Install Paru Package Manager
    shell: "yes '' | pacman -S {{ item }} | tee -a /tmp/install.log"
    with_items:
    - paru
    - base-devel
  
  - name: Update System Packages
    shell: "yes '' | paru -Syyu | tee -a /tmp/install.log"

  - name: Generate Package List
    set_fact:
      pkgList:
      - cbonsai
      - tmux
      - zsh
      - joplin-desktop
      - vivaldi
      - fish-git
      - guake
      - nvidia
      - podman
      - cowsay
      - firmware-manager
      - libfirmware-manager
      - kubectl
      - visual-studio-code-insiders-bin
      - esanso-bin
      sys76List:
      - sys76-kb
      - system76-apci-dkms
      - system76-dkms
      - system76-driver
      - system76-firmware-daemon
      - system76-io-dkms
      - system76-kbd-led-git
      - system76-power
      smartCardReaderList:
      - opensc
      - icaclient
      - pcsc-tools

  - name: Install System76 Packages (bonw14)
    shell: "yes 'y' | paru -S --skipreview {{ item }} 2>&1  | tee -a /tmp/install.log"
    with_items:
    - "{{ pkgList | join(' ') }}"
    - "{{ sys76List | join(' ') }}"
    - "{{ smartCardReaderList | join(' ') }}"
