---
- hosts: localhost
  tasks:
  - name: install packages
    command: paru -S --skipreview {{ item }}
    with_items:
    - tmux
    - zsh
    - joplin-desktop
    - vivaldi
    - guake
    - podman
    - cowsay
